[package]
name = "time-tracking-nvim-tests"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi", branch = "main", features = [
  "neovim-0-12",
  "test",
] }
time-tracking-nvim = { path = ".." }
time-tracking-cli = { git = "https://github.com/stevenwcarter/time-tracking-cli.git", branch = "main", default-features = false }
tempfile = "3.8"
time = { version = "0.3", features = ["formatting"] }

[build-dependencies]
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi", branch = "main", features = [
  "neovim-0-12",
  "test",
] }
